### ISSUE TITLE
小服务器是查不了吗

### ISSUE THREAD

**Issue by yyk725** [nonepkg/plugin-mcstatus#10]
我一个朋友开的服务器，插件的查询结果一直是off（无论实际是否在运行）

**Comment by j1g5awi** [comment]
1. 本插件无法查询基岩服，首先请确认这一点，再者查询服务器可能需要端口号。
2. 目前维护本插件并不在我的待办事项里，推荐你使用功能相似的 https://github.com/nikissXI/nonebot_plugins/tree/main/nonebot_plugin_mc_server_status
