### ISSUE TITLE
能否获取服务器的motd

### ISSUE THREAD

**Issue by FrostN0v0** [nonepkg/plugin-mcstatus#6]
mcstatus的status.raw['description']可以获取到服务器的motd，但motd如果有颜色代码，则返回的值很复杂（list套dict），能否将text数据全部提取拼接起来？

**Comment by j1g5awi** [comment]
有的服务器不支持所以就没做，你可以针对自己的服务器开发相关功能。

**Comment by FrostN0v0** [comment]
> 有的服务器不支持所以就没做，你可以针对自己的服务器开发相关功能。

做是做了一个比较烂的，能提取多数服务器的motd，还是有部分不太聪明的样子

还有，提取玩家列表的话怎么写？有无推荐方案

**Comment by j1g5awi** [comment]
也是部分服务器支持的 query，具体请看 https://github.com/py-mine/mcstatus 。
