### ISSUE TITLE
nb plugin install 后加载插件失败

### ISSUE THREAD

**Issue by Reversedeer** [nonepkg/plugin-mcstatus#9]
在windows上的linux服务器端都测试有这个问题
![QQ截图20221208104335](https://user-images.githubusercontent.com/87823528/206343815-84bb3983-462a-4169-b17f-d49624bc5bac.png)

**Comment by Reversedeer** [comment]
@nonepkg 这个问题原因
![image](https://user-images.githubusercontent.com/87823528/206347993-77e4cee5-6a3b-4f8c-ade8-d2a3462499d0.png)
能不能更新代码

**Comment by Reversedeer** [comment]
@nonepkg 这个问题原因
![image](https://user-images.githubusercontent.com/87823528/206347993-77e4cee5-6a3b-4f8c-ade8-d2a3462499d0.png)
能不能更新代码

**Comment by j1g5awi** [comment]
并非你所提及的此问题，而在于本插件依赖的 mcstatus 10.0 更改了 API
